server:
  port: 8888

spring:
  application:
    name: ssafycnt-config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  #  profiles:
  #    active: native
  cloud:
    refresh:
      extra-refreshable: com.zaxxer.hikari.HikariDataSource
    config:
      server:
        native:
          search-locations: file://config-repo
  config:
    use-legacy-processing: true
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh, info, metrics, prometheus