version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    network_mode: ssafycnt-network
    # network_mode: ssafycnt-network
    volumes:
      # - ./mysql-init-files/:/docker-entrypointinitdb.d/
      - ./mysql-data:/var/lib/mysql
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    network_mode: ssafycnt-network

volumes:
  mysql-data:

networks:
  my-network:
    name: ssafycnt-network


