FROM anapsix/alpine-java
LABEL org.opencontainers.image.authors="isakggong@gmail.com"

ARG BIN_BASE=/jarfiles

VOLUME /tmp

COPY $BIN_BASE/ssafycnt-apigateway-service-0.0.1-SNAPSHOT.jar ApiGateway.jar

# ENTRYPOINT [ "java", "-jar", "ApiGateway.jar"]
ENTRYPOINT [ "java", "-jar", "ApiGateway.jar", "--spring.profiles.active=prod"]

