FROM anapsix/alpine-java
LABEL org.opencontainers.image.authors="isakggong@gmail.com"

ARG BIN_BASE=/jarfiles

VOLUME /tmp

COPY $BIN_BASE/ssafycnt-discovery-service-0.0.1-SNAPSHOT.jar DiscoveryService.jar

# ENTRYPOINT [ "java", "-jar", "DiscoveryService.jar"]
ENTRYPOINT [ "java", "-jar", "DiscoveryService.jar", "--spring.profiles.active=prod"]
