FROM anapsix/alpine-java
LABEL org.opencontainers.image.authors="isakggong@gmail.com"

ARG BIN_BASE=/jarfiles
VOLUME /tmp

COPY $BIN_BASE/ssafycnt-config-service-0.0.1-SNAPSHOT.jar ConfigService.jar

# ENTRYPOINT [ "java", "-jar", "ConfigService.jar"]
ENTRYPOINT [ "java", "-jar", "ConfigService.jar", "--spring.profiles.active=prod"]
