FROM node as build
# Nginx 이미지
FROM nginx:1.21.0-alpine

# 빌드 결과물을 Nginx 서버에 복사
COPY --from=build /app/build /usr/share/nginx/html

# Nginx 설정 파일 복사
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 컨테이너 포트 설정
EXPOSE 80

# Nginx 실행
CMD ["nginx", "-g", "daemon off;"]
