FROM anapsix/alpine-java
LABEL org.opencontainers.image.authors="isakggong@gmail.com"

ARG BIN_BASE=/jarfiles

VOLUME /tmp

COPY $BIN_BASE/ssafycnt-user-service-0.0.1-SNAPSHOT.jar UserService.jar

# ENTRYPOINT [ "java", "-jar", "UserService.jar"]
ENTRYPOINT [ "java", "-jar", "UserService.jar", "--spring.profiles.active=prod"]
